### ISSUE TITLE
generated methods using value receiver

### ISSUE THREAD

**Issue by fearfate** [wolfogre/gtag#30]
May it be better to using value receiver `func (test) Tags()` rather than pointer receiver  `func (*test) Tags()`， for function with value receiver can be called by pointer value

**Comment by wolfogre** [comment]
You are meticulous to notice this detail. You are right, methods with a value receiver can be called by pointer variables, but methods with a pointer receiver can be called by value variables too.

I chose to use a pointer receiver because what `Tags()` returns is metadata of the struct. Therefore, it should work with values, pointers, and even nil pointers.

See https://go.dev/play/p/zU_SqU4p1sx

**Comment by fearfate** [comment]
I was mixed it up with the interface, it's my fault, close it
